/* Projects row creations */
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Mercial', 'Finance', 500.00, '04-04-2019', '01-18-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Echo', 'Social Media', 700.00, '04-09-2019', '03-20-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Facebook', 'Social Media', 500.00, '06-11-2019', '08-22-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Amazon', 'E-Commerce', 650.00, '11-24-2019', '09-02-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Snapchat', 'Social Media', 520.00, '10-08-2018', '07-01-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Twitter', 'Social Media', 230.00, '09-01-2019', '12-23-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Instagram', 'Social Media', 940.00, '06-23-2017', '01-12-2021');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('LinkedIn', 'Social Network', 1040.00, '08-12-2019', '01-18-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Spotify', 'Music Streaming', 405.00, '03-30-2018', '01-18-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Netflix', 'Video Streaming', 785.00, '02-24-2019', '01-18-2020');
/* Users row creations */
INSERT INTO users (name, age) VALUES ("Isaac", 18);
INSERT INTO users (name, age) VALUES ("Alex", 23);
INSERT INTO users (name, age) VALUES ("Nichi", 17);
INSERT INTO users (name, age) VALUES ("Mico", 11);
INSERT INTO users (name, age) VALUES ("Bean", 1);
INSERT INTO users (name, age) VALUES ("Alejandro", 42);
INSERT INTO users (name, age) VALUES ("Lorenia", 41);
INSERT INTO users (name, age) VALUES ("Sary", 35);
INSERT INTO users (name, age) VALUES ("Jorge", 37);
INSERT INTO users (name, age) VALUES ("Eli", 36);
INSERT INTO users (name, age) VALUES ("Jose Luis", 58);
INSERT INTO users (name, age) VALUES ("Irene", 57);
INSERT INTO users (name, age) VALUES ("Abigail", 37);
INSERT INTO users (name, age) VALUES ("Miguel", 17);
INSERT INTO users (name, age) VALUES ("Daniel", 38);
INSERT INTO users (name, age) VALUES ("Josue", 21);
INSERT INTO users (name, age) VALUES ("Jorge", 23);
INSERT INTO users (name, age) VALUES ("Abisai", 35);
INSERT INTO users (name, age) VALUES ("Zabdiel", 24);
INSERT INTO users (name, age) VALUES ("Atlai", 17);
/* Pledges row creations */
INSERT INTO pledges (amount, user_id, project_id) VALUES (560.00, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (670.00, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (790.00, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (820.00, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (910.00, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1090.00, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700.00, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800.00, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600.00, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500.00, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400.00, 12, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300.00, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200.00, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100.00, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50.00, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25.00, 9, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125.00, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (175.00, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (265.00, 19, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450.00, 20, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (740.00, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (230.00, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (770.00, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1120.00, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (405.00, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (780.00, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (290.00, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (320.00, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (440.00, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (680.00, 16, 7);
